# Azure DevOps pipeline for automating purge durable functions history.
#
# The following parameter needs to be set to identify the environment for which
# should be ordered or renewed a certificate via ACME:
# - ENVIRONMENT: TEST | PRODUCTION
#
# The following pipeline variables have to be added and configured based on the
# environment:
# - PRODUCTION_AZURE_SUBSCRIPTION: service connection name
# - TEST_AZURE_SUBSCRIPTION: service connection name for test only

parameters:
  - name: 'ENVIRONMENT'
    displayName: 'Select the environment for which purge durable function history:'
    type: string
    default: DEV-SERVICE_PRINCIPAL-CONNECTION
    values:
      - DEV-SERVICE_PRINCIPAL-CONNECTION
      - PROD-IO-SERVICE-CONN_FAKE
      - DEV-IO-SERVICE-CONN_FAKE
      
  - name: 'DRY_RUN'
    displayName: 'Select the environment for which purge durable function history:'
    type: boolean
    default: false
  
pool:
  vmImage: 'ubuntu-latest'

# The scheduled trigger will be set in the Azure DevOps portal
trigger:
  batch: true
  branches:
    include:
    - master

jobs:
  - job: purge_df_history
    steps:
      # 1. Set the number of the run
      - task: PowerShell@2
        displayName: Update Run Number
        inputs:
          targetType: 'inline'
          script: '$id = "$(Build.BuildId)"; $date = Get-Date -Format "yyyy.MMdd"; Write-Host "##vso[build.updatebuildnumber]$date.$id"'

      # 2. Install the Azure Functions Core Tools our script will need
      - task: FuncToolsInstaller@0
        displayName: Install Azure Functions Core Tools

      # 3. Purge History
      - task: AzureCLI@2
        displayName: Purge History
        inputs:
          azureSubscription: '${{ parameters.ENVIRONMENT }}'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          failOnStandardError: true
          inlineScript: |
            for policy in policies/*
            do
              bash src/purge-history.sh ${policy}
            done
