# Azure DevOps pipeline for automating purge durable functions history.
# All files with .env in policies folder are applied.
#
# The following parameter needs to be set to identify the Azure subscription :
# - SUBSCRIPTION: PROD-IO-SERVICE-CONN | DEV-IO-SERVICE-CONN
#
# The following pipeline parameters have to be setted for manual execution:
# - SUBSCRIPTION: service connection name
# - DRY_RUN: run pipeline without apply any changes

# The scheduled trigger will be set in the Azure DevOps portal
trigger: none
pr: none

pool:
  vmImage: 'ubuntu-latest'
# pool:
#   name: 'io-prod-linux' #$(AGENT_POOL)

jobs:
  - job: purge_df_history
    steps:
      # 1. Install the Azure Functions Core Tools our script will need
      - task: FuncToolsInstaller@0
        displayName: Install Azure Functions Core Tools
        inputs:
          version: '3.0.3904'
      # 2. Purge History
      - task: AzureCLI@2
        displayName: Purge History
        env:
          STORAGE_ACCOUNT: $(STORAGE_ACCOUNT)
          TASK_HUB: $(TASK_HUB)
          DRY_RUN: $(DRY_RUN)
          LIST_STATUS: $(LIST_STATUS)
          DAYS_BEFORE: $(DAYS_BEFORE)
          NO_CACHE: $(NO_CACHE)
        inputs:
          azureSubscription: '$(SUBSCRIPTION)'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          failOnStandardError: true
          inlineScript: |
            bash src/purge-history.sh policies/default_policy.env
