# Azure DevOps pipeline for automating purge durable functions history.
#
# The following parameter needs to be set to identify the environment for which
# should be ordered or renewed a certificate via ACME:
# - ENVIRONMENT: TEST | PRODUCTION
#
# The following pipeline variables have to be added and configured based on the
# environment:
# - PRODUCTION_AZURE_SUBSCRIPTION: service connection name
# - TEST_AZURE_SUBSCRIPTION: service connection name for test only

parameters:
  - name: 'ENVIRONMENT'
    displayName: 'Select the environment for which purge durable function history:'
    type: string
    default: DEV-SERVICE_PRINCIPAL-CONNECTION
    values:
      - DEV-SERVICE_PRINCIPAL-CONNECTION
      - PROD-IO-SERVICE-CONN_FAKE
      - DEV-IO-SERVICE-CONN_FAKE

  - name: 'DRY_RUN'
    displayName: 'Dry run do not apply changes'
    type: boolean
    default: false

  - name: 'STORAGE_ACCOUNT'
    displayName: 'Set Storage Account name:'
    type: string

  - name: 'TASK_HUB'
    displayName: 'Set TaskHub name:'
    type: string

  - name: 'NO_DATE_FILTER'
    displayName: 'Apply purge without date filter (ignore days before)'
    type: boolean
    default: false

  - name: 'DAYS_BEFORE'
    displayName: 'Set days before:'
    type: number
    default: 30

  - name: 'NO_STATUS_FILTER'
    displayName: 'Apply purge to all status (ignore status)'
    type: boolean
    default: false

  - name: 'LIST_STATUS'
    displayName: 'Set status:'
    type: string
    values:
      - completed
      - terminated
      - canceled
      - failed

variables:
  - name: 'DRY_RUN'
    value: '${{ parameters.DRY_RUN }}'
  - name: 'STORAGE_ACCOUNT'
    value: '${{ parameters.STORAGE_ACCOUNT }}'
  - name: 'TASK_HUB'
    value: '${{ parameters.TASK_HUB }}'
  - name: 'NO_DATE_FILTER'
    value: '${{ parameters.NO_DATE_FILTER }}'
  - name: 'DAYS_BEFORE'
    value: '${{ parameters.DAYS_BEFORE }}'
  - name: 'NO_STATUS_FILTER'
    value: '${{ parameters.NO_STATUS_FILTER }}'
  - name: 'LIST_STATUS'
    value: '${{ parameters.LIST_STATUS }}'

pool:
  vmImage: 'ubuntu-latest'

# Manual execution
trigger: none

jobs:
  - job: purge_df_history
    steps:
      # 1. Set the number of the run
      - task: PowerShell@2
        displayName: Update Run Number
        inputs:
          targetType: 'inline'
          script: '$id = "$(Build.BuildId)"; $date = Get-Date -Format "yyyy.MMdd"; Write-Host "##vso[build.updatebuildnumber]$date.$id"'

      # 2. Install the Azure Functions Core Tools our script will need
      - task: FuncToolsInstaller@0
        displayName: Install Azure Functions Core Tools

      # 3. Purge History
      - task: AzureCLI@2
        displayName: Purge History
        inputs:
          azureSubscription: '${{ parameters.ENVIRONMENT }}'
          scriptType: 'bash'
          scriptLocation: 'inlineScript'
          failOnStandardError: true
          inlineScript: |
            bash src/configure-manual.sh policies/tmp-manual.env
            bash src/purge-history.sh policies/tmp-manual.env
